routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/
Route::get('/', 'MainController@index');
Route::get('/states', 'MainController@states');
Route::get('/countries', 'MainController@countries');
Route::get('/refreshdb', 'MainController@refreshdb');

app/State.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
    public $timestamps = false;

    /**
     * Get the tax states for the country.
     */
    public function counties()
    {
        return $this->hasMany('App\County', 'state_id', 'id');
    }

    public function country() {
        return $this->belongsTo('App\Country');
    }

    public function tax_rates() {
        return $this->hasManyThrough('App\TaxRate', 'App\County');
    }

    public function getAvgCountyTaxRateAttribute() {
        return $this->tax_rates()->avg('rate');
    }

    public function tax_payers() {
        return $this->hasManyThrough('App\TaxPayer', 'App\County');
    }

    public function getTotalIncomeAttribute() {
        return $this->tax_payers()->sum('income');
    }

    public function getOverallTaxAttribute() {
        $tax_payers = $this->tax_payers()->get();
        $sum = 0;
        foreach( $tax_payers as $tax_payer ) {
            $sum += ( $tax_payer->tax_rate->rate * $tax_payer->income ) / 100;
        }
        return $sum;
    }

    public function getTaxPayerCountAttribute() {
        return $this->tax_payers()->count();
    }

    public function getAvgTaxPerPersonAttribute() {
        return $this->getOverallTaxAttribute()/$this->getTaxPayerCountAttribute();
    }
}

app/TaxPayer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TaxPayer extends Model
{
    public $timestamps = false;

    public function county() {
        return $this->belongsTo('App\County');
    }


    public function state()
    {
        return $this->belongsTo('App\County');
    }

    public function tax_rates()
    {

        return $this->hasMany('App\TaxRate', 'county_id', 'county_id');
    }


    public function tax_rate()
    {
        return $this->hasOne( 'App\TaxRate', 'county_id', 'county_id' )
            ->where('above', '<', $this->income )
            ->orderBy('above', 'desc');
    }

    public function getTaxAttribute(){
        return  $this->tax_rate->rate*$this->income/100;
    }

    public function getNetIncomeAttribute(){
        return   $this->income-$this->tax;
    }

    public function getStateNameAttribute(){
        return  $this->county->state->name;
    }

    public function getCountryNameAttribute(){
        return  $this->county->state->country->name;
    }

    public function net_income() {
        return ( $this->income-$this->tax()->rate );
    }
}

resources/views/countries.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>

                        @if (Route::has('register'))
                            <a href="{{ route('register') }}">Register</a>
                        @endif
                    @endauth
                </div>
            @endif

            <div class="content">
                @include('navmenu')
                <div class="title m-b-md">
                    The Tax Calculator - Per Country
                </div>
                <div class="text-body">
                    @if (count($countries))
                        <table border="1" cellspacing="1" cellpadding="5">
                            <tr>
                                <th> ID </th>
                                <th> OVERALL TAX </th>
                                <th> OVERALL INCOME </th>
                                <th> AVERAGE TAX PER PERSON </th>
                                <th> AVERAGE COUNTY TAX RATE </th>
                                <th> TAX PAYER COUNT </th>
                                <th> COUNTRY </th>
                            </tr>
                        @foreach($countries as $country)
                            <tr>
                                <td>{{ $country->id }}</td>
                                <?php /*
                                <td>{{ number_format( $country->overall_tax, 2 ) }}</td>
                                <td>{{ number_format( $country->total_income, 2 ) }}</td>
                                <td>{{ number_format( $country->avg_tax_per_person, 2 ) }}</td>
                                <td>{{ number_format( $country->avg_county_tax_rate, 2 ) }}</td>
 */ ?>
                                <td>{{ number_format( $country->overall_tax, 2 ) }}</td>
                                <td>{{ number_format( $country->total_income, 2 ) }}</td>
                                <td>{{ number_format( $country->avg_tax_per_person, 2 ) }}</td>
                                <td>{{ number_format( $country->avg_county_tax_rate, 2 ) }}</td>
                                <td>{{ $country->tax_payer_count }}</td>
                                <td>{{ $country->name }}</td>

                            </tr>
                        @endforeach
                        </table>
                    @else
                        <p>No Tax Payers.</p>
                    @endif
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/navmenu.blade.php
<div class="links" style="padding-top: 10px;">
    <a href="/">Tax Payers</a>
    <a href="/states">States</a>
    <a href="/countries">Countries</a>
    <a href="/refreshdb">DB Refresh & Seed</a>
</div>

resources/views/states.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>

                        @if (Route::has('register'))
                            <a href="{{ route('register') }}">Register</a>
                        @endif
                    @endauth
                </div>
            @endif

            <div class="content">
                @include('navmenu')
                <div class="title m-b-md">
                    The Tax Calculator - Per State
                </div>
                <div class="text-body">
                    @if (count($countries))
                        <table border="1" cellspacing="1" cellpadding="5">
                            <tr>
                                <th> ID </th>
                                <th> OVERALL TAX </th>
                                <th> OVERALL INCOME </th>
                                <th> AVERAGE TAX PER PERSON </th>
                                <th> AVERAGE COUNTY TAX RATE </th>
                                <th> TAX PAYER COUNT </th>
                                <th> STATE </th>
                                <th> COUNTRY </th>
                            </tr>
                        @foreach($countries as $country)
                            @foreach( $country->states as $state)
                            <tr>
                                <td>{{ $state->id }}</td>
                                <td>{{ number_format( $state->overall_tax, 2 ) }}</td>
                                <td>{{ number_format( $state->total_income, 2 ) }}</td>
                                <td>{{ number_format( $state->avg_tax_per_person, 2 ) }}</td>
                                <td>{{ number_format( $state->avg_county_tax_rate, 2 ) }}</td>
                                <td>{{ $state->tax_payer_count }}</td>
                                <td>{{ $state->name }}</td>
                                <td>{{ $country->name }}</td>

                            </tr>
                            @endforeach
                        @endforeach
                        </table>
                    @else
                        <p>No Tax Payers.</p>
                    @endif
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/taxpayers.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>

                        @if (Route::has('register'))
                            <a href="{{ route('register') }}">Register</a>
                        @endif
                    @endauth
                </div>
            @endif

            <div class="content">
                @include('navmenu')
                <div class="title m-b-md">
                    The Tax Calculator - Tax Payers
                </div>
                <div class="text-body">
                    @if (count($tax_payers))
                        <table border="1" cellspacing="1" cellpadding="5">
                            <tr>
                                <th> ID </th>
                                <th> NAME </th>
                                <th> INCOME </th>
                                <th> NET INCOME </th>
                                <th> TAX </th>
                                <th> TAX RATE </th>
                                <th> TAX CATEGORY </th>
                                <th> TAX ID </th>
                                <th> COUNTY </th>
                                <th> STATE </th>
                                <th> COUNTRY </th>
                            </tr>
                        @foreach($tax_payers as $tax_payer)
                            <tr>
                                <td>{{ $tax_payer->id }}</td>
                                <td>{{ $tax_payer->name }}</td>
                                <td>{{ number_format( $tax_payer->income, 2 ) }}</td>
                                <td>{{ number_format( $tax_payer->net_income, 2 ) }} </td>
                                <td>{{ number_format( $tax_payer->tax, 2 ) }}</td>
                                <td>{{ $tax_payer->tax_rate->rate }}</td>
                                <td align="center"> < €{{ number_format( $tax_payer->tax_rate->below ) }} <br /> > €{{ number_format( $tax_payer->tax_rate->above ) }} </td>
                                <td>{{ $tax_payer->tax_rate->id }}</td>
                                <td>{{ $tax_payer->county->name }}</td>
                                <td>{{ $tax_payer->state_name }}</td>
                                <td>{{ $tax_payer->country_name }}</td>

                            </tr>
                        @endforeach
                        </table>
                    @else
                        <p>No Tax Payers.</p>
                    @endif
                </div>
            </div>
        </div>
    </body>
</html>